<a href="https://colab.research.google.com/github/aini43325018-ui/2025_algoritma_dan_pemrograman/blob/Kecerdasan-Buatan---Semester-2/AI_Jobsheet_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Latihan 01: Tipe Data Python

In [ ]:
# Cek Tipe Data

var = 123
print(type(var))

# Tipe Data String

a = '123'
b = '3.4'
c = "Data String"
print(type(c))

# Tipe Data Numerik

var1 = 345
var2 = 34.5
f1 = float(var1)
print(type(f1))
print(f1)
sum = var1 + var2
print(sum)
var3 = 12.3
var4 = 12.9
i1 = int(var2)
i2 = int(var3)
print(i1)
print(i2)

# Tipe Data Boolean

print(var1 == var2)
print(var1 < var2)
print(var1 > var2)
print(var1 != var2)

# Tipe Data List

list = ["belajar dasar python", 2023, 3.8, True]
print(list)
print(list[3])
print(list[1:3])
print(len(list))

<class 'int'>
<class 'str'>
<class 'float'>
345.0
379.5
34
12
False
False
True
True
['belajar dasar python', 2023, 3.8, True]
True
[2023, 3.8]
4


Latihan 02: Operasi Matematika Menggunakan Python

In [ ]:
# Mendapatkan nilai minimum dan maksimum

print("Mendapatkan nilai minimum dan maksimum")
x = min(5, 10, 25)
y = max(6, 12, 18)
print("Nilai minimum (x) :", x)
print("Nilai maksimum (y) :", y)

# Mendapatkan nilai absolut

print("\nMendapatkan nilai absolut")
x = abs(-7.25)
print("Nilai absolut (x)  :", x)

# Mendapatkan nilai pangkat

print("\nMendapatkan nilai pangkat")
import math
x = math.pow(4, 3)
print("4 pangkat 3 (x)    :", x)

# Mendapatkan nilai pembulatan

print("\nMendapatkan nilai pembulatan")
import math
x = math.ceil(1.4)
print("Bulat ke atas (x)  :", x)
y = math.floor(1.4)
print("Bulat ke bawah (y) :", y)

# Mendapatkan nilai konstanta (PI)

print("\nMendapatkan nilai konstanta (PI)")
import math
x = math.pi
print("Nilai konstanta PI :", x)



Mendapatkan nilai minimum dan maksimum
Nilai minimum (x) : 5
Nilai maksimum (y) : 18

Mendapatkan nilai absolut
Nilai absolut (x)  : 7.25

Mendapatkan nilai pangkat
4 pangkat 3 (x)    : 64.0

Mendapatkan nilai pembulatan
Bulat ke atas (x)  : 2
Bulat ke bawah (y) : 1

Mendapatkan nilai konstanta (PI)
Nilai konstanta PI : 3.141592653589793


Latihan 03: Menggunakan Fungsi MATH

In [ ]:
# 1. math.sin() -> Menghitung sinus (dalam radian)
print("Sinus 90 derajat:", math.sin(math.radians(90)))

# 2. math.cos() -> Menghitung cosinus (dalam radian)
print("Cosinus 0 derajat:", math.cos(math.radians(0)))

# 3. math.tan() -> Menghitung tangen (dalam radian)
print("Tangen 45 derajat:", math.tan(math.radians(45)))

# 4. math.log() -> Logaritma natural (basis e)
print("Logaritma natural dari 10:", math.log(10))

# 5. math.log10() -> Logaritma basis 10
print("Logaritma basis 10 dari 100:", math.log10(100))

# 6. math.degrees() -> Mengubah radian ke derajat
print("Radian (pi) ke Derajat:", math.degrees(math.pi))

# 7. math.dist() -> Menghitung jarak Euclidean antara dua titik [x,y]
titik1 = [0, 0]
titik2 = [3, 4]
print("Jarak antara titik (0,0) dan (3,4):", math.dist(titik1, titik2))

# 8. math.factorial() -> Menghitung faktorial
print("Faktorial dari 5 (5!):", math.factorial(5))

# 9. math.fmod() -> Menghitung sisa bagi (modulus) angka desimal
print("Sisa bagi 10.5 dengan 3:", math.fmod(10.5, 3))

# 10. math.isnan() -> Mengecek apakah nilai tersebut 'Not a Number' (NaN)
print("Apakah 'NaN' itu NaN?:", math.isnan(float('nan')))

# 11. math.gamma() -> Menghitung fungsi Gamma
print("Fungsi Gamma dari 6:", math.gamma(6))

# 12. math.perm() -> Menghitung permutasi (nPk)
# Contoh: 5P2 (Permutasi 2 dari 5 objek)
print("Permutasi 5P2:", math.perm(5, 2))

Sinus 90 derajat: 1.0
Cosinus 0 derajat: 1.0
Tangen 45 derajat: 0.9999999999999999
Logaritma natural dari 10: 2.302585092994046
Logaritma basis 10 dari 100: 2.0
Radian (pi) ke Derajat: 180.0
Jarak antara titik (0,0) dan (3,4): 5.0
Faktorial dari 5 (5!): 120
Sisa bagi 10.5 dengan 3: 1.5
Apakah 'NaN' itu NaN?: True
Fungsi Gamma dari 6: 120.0
Permutasi 5P2: 20


Latihan 04: Operasi Matriks dan Vektor dengan Python

In [ ]:
# Membuat Matriks di Python

import numpy as np
A = np.array ([[80, 30, 25],
               [50, 20, 10]])
B = np.array([[30, 60, 15],
              [10, 30, 30]])

hasil = A  + B

print("\nMatriks A")
print(A)

# Menampilkan Matriks B
print("\nMatriks B")
print(B)

# Menampilkan Hasil Penjumlahan
print("\nHasil Penjumlahan (A + B)")
print(hasil)

# Melakukan Operasi Dot Product

import numpy as np
A = np.array([10, 20, 15])
B = np.array([16, 67, 35])

hasil = np.dot(A, B)

print("\nHasil Dot Product (A.B)")
print(hasil)

# Melakukan Operasi Cross Product

import numpy as np
A = np.array([10, 20, 15])
B = np.array([16, 67, 35])

hasil = np.cross(A, B)

print("\nHasil Cross Product (A x B)")
print(hasil)


Matriks A
[[80 30 25]
 [50 20 10]]

Matriks B
[[30 60 15]
 [10 30 30]]

Hasil Penjumlahan (A + B)
[[110  90  40]
 [ 60  50  40]]

Hasil Dot Product (A.B)
2025

Hasil Cross Product (A x B)
[-305 -110  350]


Praktikum 01: Operasi Matriks


In [ ]:
import numpy as np
import math

# Definisi Matriks
A_mat = np.array([[3,1], [2, 0]])
B_mat = np.array([[2, 1], [1, -1]])
C_mat = np.array([[-1, 1, 2], [2, 0, -1]])

# 1a

hasil_AxB = np.matmul(A_mat, B_mat)
print("Hasil A x B:\n", hasil_AxB)

# 1b

hasil_BC = np.matmul(B_mat, C_mat)
print("\nHasil B . C:\n", hasil_BC)

Hasil A x B:
 [[7 2]
 [4 2]]

Hasil B . C:
 [[ 0  2  3]
 [-3  1  3]]


Praktikum 02: Faktorial

In [ ]:
# 2a

faktorial_6 = math.factorial(6)
print(f"\nHasil 6!: {faktorial_6}")

# 2b

faktorial_8_5 = math.factorial(8) / math.factorial(5)
print(f"Hasil 8! / 5!: {faktorial_8_5}")


Hasil 6!: 720
Hasil 8! / 5!: 336.0


Praktikum 03: Operasi Vektor 3D

In [ ]:
vec_A = np.array([5, 3, 7])
vec_B = np.array([12, -3, 1])

panjang_A = np.linalg.norm(vec_A)
panjang_B = np.linalg.norm(vec_B)
print(f"\nPanjang vektor A: {panjang_A}")
print(f"Panjang vektor B: {panjang_B}")

titik_AB = np.dot(vec_A, vec_B)
print(f"Hasil A.B (Dot Product): {titik_AB}")

silang_AB = np.cross(vec_A, vec_B)
print(f"Hasil A x B (Cross Product): {silang_AB}")


Panjang vektor A: 9.1104335791443
Panjang vektor B: 12.409673645990857
Hasil A.B (Dot Product): 58
Hasil A x B (Cross Product): [ 24  79 -51]
